-- *************************************************************************************************
--   This source member will insert data into GEOCNTT.
--
-- @author James Brian Hill
-- @copyright Copyright (c) 2015 - 2025 by James Brian Hill
-- @license GNU General Public License version 3
-- @link https://www.gnu.org/licenses/gpl-3.0.html
-- *************************************************************************************************

-- *************************************************************************************************
--   This program is free software: you can redistribute it and/or modify it under the terms of the
-- GNU General Public License as published by the Free Software Foundation, either version 3 of the
-- License, or (at your option) any later version.
--
--   This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-- without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-- GNU General Public License for more details.
--
--   You should have received a copy of the GNU General Public License along with this program. If
-- not, see https://www.gnu.org/licenses/gpl-3.0.html
-- *************************************************************************************************
INSERT INTO geocntt (id, iso3, isonum, name, tld) VALUES
('AD', 'AND', '020', 'Andorra', 'ad'),
('AE', 'ARE', '784', 'United Arab Emirates', 'ae'),
('AF', 'AFG', '004', 'Afghanistan', 'af'),
('AG', 'ATG', '028', 'Antigua and Barbuda', 'ag'),
('AI', 'AIA', '660', 'Anguilla', 'ai'),
('AL', 'ALB', '008', 'Albania', 'al'),
('AM', 'ARM', '051', 'Armenia', 'am'),
('AO', 'AGO', '024', 'Angola', 'ao'),
('AQ', 'ATA', '010', 'Antarctica', 'aq'),
('AR', 'ARG', '032', 'Argentina', 'ar'),
('AS', 'ASM', '016', 'American Samoa', 'as'),
('AT', 'AUT', '040', 'Austria', 'at'),
('AU', 'AUS', '036', 'Australia', 'au'),
('AW', 'ABW', '533', 'Aruba', 'aw'),
('AX', 'ALA', '248', 'Åland Islands', 'ax'),
('AZ', 'AZE', '031', 'Azerbaijan', 'az'),
('BA', 'BIH', '070', 'Bosnia and Herzegovina', 'ba'),
('BB', 'BRB', '052', 'Barbados', 'bb'),
('BD', 'BGD', '050', 'Bangladesh', 'bd'),
('BE', 'BEL', '056', 'Belgium', 'be'),
('BF', 'BFA', '854', 'Burkina Faso', 'bf'),
('BG', 'BGR', '100', 'Bulgaria', 'bg'),
('BH', 'BHR', '048', 'Bahrain', 'bh'),
('BI', 'BDI', '108', 'Burundi', 'bi'),
('BJ', 'BEN', '204', 'Benin', 'bj'),
('BL', 'BLM', '652', 'Saint Barthélemy', 'bl'),
('BM', 'BMU', '060', 'Bermuda', 'bm'),
('BN', 'BRN', '096', 'Brunei Darussalam', 'bn'),
('BO', 'BOL', '068', 'Bolivia, Plurinational State of', 'bo'),
('BQ', 'BES', '535', 'Bonaire, Sint Eustatius and Saba', 'bq'),
('BR', 'BRA', '076', 'Brazil', 'br'),
('BS', 'BHS', '044', 'Bahamas', 'bs'),
('BT', 'BTN', '064', 'Bhutan', 'bt'),
('BV', 'BVT', '074', 'Bouvet Island', 'bv'),
('BW', 'BWA', '072', 'Botswana', 'bw'),
('BY', 'BLR', '112', 'Belarus', 'by'),
('BZ', 'BLZ', '084', 'Belize', 'bz'),
('CA', 'CAN', '124', 'Canada', 'ca'),
('CC', 'CCK', '166', 'Cocos (Keeling) Islands', 'cc'),
('CD', 'COD', '180', 'Congo, Democratic Republic of the', 'cd'),
('CF', 'CAF', '140', 'Central African Republic', 'cf'),
('CG', 'COG', '178', 'Congo', 'cg'),
('CH', 'CHE', '756', 'Switzerland', 'ch'),
('CI', 'CIV', '384', 'Côte d''Ivoire', 'ci'),
('CK', 'COK', '184', 'Cook Islands', 'ck'),
('CL', 'CHL', '152', 'Chile', 'cl'),
('CM', 'CMR', '120', 'Cameroon', 'cm'),
('CN', 'CHN', '156', 'China', 'cn'),
('CO', 'COL', '170', 'Colombia', 'co'),
('CR', 'CRI', '188', 'Costa Rica', 'cr'),
('CU', 'CUB', '192', 'Cuba', 'cu'),
('CV', 'CPV', '132', 'Cabo Verde', 'cv'),
('CW', 'CUW', '531', 'Curaçao', 'cw'),
('CX', 'CXR', '162', 'Christmas Island', 'cx'),
('CY', 'CYP', '196', 'Cyprus', 'cy'),
('CZ', 'CZE', '203', 'Czechia', 'cz'),
('DE', 'DEU', '276', 'Germany', 'de'),
('DJ', 'DJI', '262', 'Djibouti', 'dj'),
('DK', 'DNK', '208', 'Denmark', 'dk'),
('DM', 'DMA', '212', 'Dominica', 'dm'),
('DO', 'DOM', '214', 'Dominican Republic', 'do'),
('DZ', 'DZA', '012', 'Algeria', 'dz'),
('EC', 'ECU', '218', 'Ecuador', 'ec'),
('EE', 'EST', '233', 'Estonia', 'ee'),
('EG', 'EGY', '818', 'Egypt', 'eg'),
('EH', 'ESH', '732', 'Western Sahara', 'eh'),
('ER', 'ERI', '232', 'Eritrea', 'er'),
('ES', 'ESP', '724', 'Spain', 'es'),
('ET', 'ETH', '231', 'Ethiopia', 'et'),
('FI', 'FIN', '246', 'Finland', 'fi'),
('FJ', 'FJI', '242', 'Fiji', 'fj'),
('FK', 'FLK', '238', 'Falkland Islands (Malvinas)', 'fk'),
('FM', 'FSM', '583', 'Micronesia, Federated States of', 'fm'),
('FO', 'FRO', '234', 'Faroe Islands', 'fo'),
('FR', 'FRA', '250', 'France', 'fr'),
('GA', 'GAB', '266', 'Gabon', 'ga'),
('GB', 'GBR', '826', 'United Kingdom of Great Britain and Northern Ireland', 'uk'),
('GD', 'GRD', '308', 'Grenada', 'gd'),
('GE', 'GEO', '268', 'Georgia', 'ge'),
('GF', 'GUF', '254', 'French Guiana', 'gf'),
('GG', 'GGY', '831', 'Guernsey', 'gg'),
('GH', 'GHA', '288', 'Ghana', 'gh'),
('GI', 'GIB', '292', 'Gibraltar', 'gi'),
('GL', 'GRL', '304', 'Greenland', 'gl'),
('GM', 'GMB', '270', 'Gambia', 'gm'),
('GN', 'GIN', '324', 'Guinea', 'gn'),
('GP', 'GLP', '312', 'Guadeloupe', 'gp'),
('GQ', 'GNQ', '226', 'Equatorial Guinea', 'gq'),
('GR', 'GRC', '300', 'Greece', 'gr'),
('GS', 'SGS', '239', 'South Georgia and the South Sandwich Islands', 'gs'),
('GT', 'GTM', '320', 'Guatemala', 'gt'),
('GU', 'GUM', '316', 'Guam', 'gu'),
('GW', 'GNB', '624', 'Guinea-Bissau', 'gw'),
('GY', 'GUY', '328', 'Guyana', 'gy'),
('HK', 'HKG', '344', 'Hong Kong', 'hk'),
('HM', 'HMD', '334', 'Heard Island and McDonald Islands', 'hm'),
('HN', 'HND', '340', 'Honduras', 'hn'),
('HR', 'HRV', '191', 'Croatia', 'hr'),
('HT', 'HTI', '332', 'Haiti', 'ht'),
('HU', 'HUN', '348', 'Hungary', 'hu'),
('ID', 'IDN', '360', 'Indonesia', 'id'),
('IE', 'IRL', '372', 'Ireland', 'ie'),
('IL', 'ISR', '376', 'Israel', 'il'),
('IM', 'IMN', '833', 'Isle of Man', 'im'),
('IN', 'IND', '356', 'India', 'in'),
('IO', 'IOT', '086', 'British Indian Ocean Territory', 'io'),
('IQ', 'IRQ', '368', 'Iraq', 'iq'),
('IR', 'IRN', '364', 'Iran, Islamic Republic of', 'ir'),
('IS', 'ISL', '352', 'Iceland', 'is'),
('IT', 'ITA', '380', 'Italy', 'it'),
('JE', 'JEY', '832', 'Jersey', 'je'),
('JM', 'JAM', '388', 'Jamaica', 'jm'),
('JO', 'JOR', '400', 'Jordan', 'jo'),
('JP', 'JPN', '392', 'Japan', 'jp'),
('KE', 'KEN', '404', 'Kenya', 'ke'),
('KG', 'KGZ', '417', 'Kyrgyzstan', 'kg'),
('KH', 'KHM', '116', 'Cambodia', 'kh'),
('KI', 'KIR', '296', 'Kiribati', 'ki'),
('KM', 'COM', '174', 'Comoros', 'km'),
('KN', 'KNA', '659', 'Saint Kitts and Nevis', 'kn'),
('KP', 'PRK', '408', 'Korea, Democratic People''s Republic of', 'kp'),
('KR', 'KOR', '410', 'Korea, Republic of', 'kr'),
('KW', 'KWT', '414', 'Kuwait', 'kw'),
('KY', 'CYM', '136', 'Cayman Islands', 'ky'),
('KZ', 'KAZ', '398', 'Kazakhstan', 'kz'),
('LA', 'LAO', '418', 'Lao People''s Democratic Republic', 'la'),
('LB', 'LBN', '422', 'Lebanon', 'lb'),
('LC', 'LCA', '662', 'Saint Lucia', 'lc'),
('LI', 'LIE', '438', 'Liechtenstein', 'li'),
('LK', 'LKA', '144', 'Sri Lanka', 'lk'),
('LR', 'LBR', '430', 'Liberia', 'lr'),
('LS', 'LSO', '426', 'Lesotho', 'ls'),
('LT', 'LTU', '440', 'Lithuania', 'lt'),
('LU', 'LUX', '442', 'Luxembourg', 'lu'),
('LV', 'LVA', '428', 'Latvia', 'lv'),
('LY', 'LBY', '434', 'Libya', 'ly'),
('MA', 'MAR', '504', 'Morocco', 'ma'),
('MC', 'MCO', '492', 'Monaco', 'mc'),
('MD', 'MDA', '498', 'Moldova, Republic of', 'md'),
('ME', 'MNE', '499', 'Montenegro', 'me'),
('MF', 'MAF', '663', 'Saint Martin (French part)', 'mf'),
('MG', 'MDG', '450', 'Madagascar', 'mg'),
('MH', 'MHL', '584', 'Marshall Islands', 'mh'),
('MK', 'MKD', '807', 'North Macedonia', 'mk'),
('ML', 'MLI', '466', 'Mali', 'ml'),
('MM', 'MMR', '104', 'Myanmar', 'mm'),
('MN', 'MNG', '496', 'Mongolia', 'mn'),
('MO', 'MAC', '446', 'Macao', 'mo'),
('MP', 'MNP', '580', 'Northern Mariana Islands', 'mp'),
('MQ', 'MTQ', '474', 'Martinique', 'mq'),
('MR', 'MRT', '478', 'Mauritania', 'mr'),
('MS', 'MSR', '500', 'Montserrat', 'ms'),
('MT', 'MLT', '470', 'Malta', 'mt'),
('MU', 'MUS', '480', 'Mauritius', 'mu'),
('MV', 'MDV', '462', 'Maldives', 'mv'),
('MW', 'MWI', '454', 'Malawi', 'mw'),
('MX', 'MEX', '484', 'Mexico', 'mx'),
('MY', 'MYS', '458', 'Malaysia', 'my'),
('MZ', 'MOZ', '508', 'Mozambique', 'mz'),
('NA', 'NAM', '516', 'Namibia', 'na'),
('NC', 'NCL', '540', 'New Caledonia', 'nc'),
('NE', 'NER', '562', 'Niger', 'ne'),
('NF', 'NFK', '574', 'Norfolk Island', 'nf'),
('NG', 'NGA', '566', 'Nigeria', 'ng'),
('NI', 'NIC', '558', 'Nicaragua', 'ni'),
('NL', 'NLD', '528', 'Netherlands, Kingdom of the', 'nl'),
('NO', 'NOR', '578', 'Norway', 'no'),
('NP', 'NPL', '524', 'Nepal', 'np'),
('NR', 'NRU', '520', 'Nauru', 'nr'),
('NU', 'NIU', '570', 'Niue', 'nu'),
('NZ', 'NZL', '554', 'New Zealand', 'nz'),
('OM', 'OMN', '512', 'Oman', 'om'),
('PA', 'PAN', '591', 'Panama', 'pa'),
('PE', 'PER', '604', 'Peru', 'pe'),
('PF', 'PYF', '258', 'French Polynesia', 'pf'),
('PG', 'PNG', '598', 'Papua New Guinea', 'pg'),
('PH', 'PHL', '608', 'Philippines', 'ph'),
('PK', 'PAK', '586', 'Pakistan', 'pk'),
('PL', 'POL', '616', 'Poland', 'pl'),
('PM', 'SPM', '666', 'Saint Pierre and Miquelon', 'pm'),
('PN', 'PCN', '612', 'Pitcairn', 'pn'),
('PR', 'PRI', '630', 'Puerto Rico', 'pr'),
('PS', 'PSE', '275', 'Palestine, State of', 'ps'),
('PT', 'PRT', '620', 'Portugal', 'pt'),
('PW', 'PLW', '585', 'Palau', 'pw'),
('PY', 'PRY', '600', 'Paraguay', 'py'),
('QA', 'QAT', '634', 'Qatar', 'qa'),
('RE', 'REU', '638', 'Réunion', 're'),
('RO', 'ROU', '642', 'Romania', 'ro'),
('RS', 'SRB', '688', 'Serbia', 'rs'),
('RU', 'RUS', '643', 'Russian Federation', 'ru'),
('RW', 'RWA', '646', 'Rwanda', 'rw'),
('SA', 'SAU', '682', 'Saudi Arabia', 'sa'),
('SB', 'SLB', '090', 'Solomon Islands', 'sb'),
('SC', 'SYC', '690', 'Seychelles', 'sc'),
('SD', 'SDN', '729', 'Sudan', 'sd'),
('SE', 'SWE', '752', 'Sweden', 'se'),
('SG', 'SGP', '702', 'Singapore', 'sg'),
('SH', 'SHN', '654', 'Saint Helena, Ascension and Tristan da Cunha', 'sh'),
('SI', 'SVN', '705', 'Slovenia', 'si'),
('SJ', 'SJM', '744', 'Svalbard and Jan Mayen', 'sj'),
('SK', 'SVK', '703', 'Slovakia', 'sk'),
('SL', 'SLE', '694', 'Sierra Leone', 'sl'),
('SM', 'SMR', '674', 'San Marino', 'sm'),
('SN', 'SEN', '686', 'Senegal', 'sn'),
('SO', 'SOM', '706', 'Somalia', 'so'),
('SR', 'SUR', '740', 'Suriname', 'sr'),
('SS', 'SSD', '728', 'South Sudan', 'ss'),
('ST', 'STP', '678', 'Sao Tome and Principe', 'st'),
('SV', 'SLV', '222', 'El Salvador', 'sv'),
('SX', 'SXM', '534', 'Sint Maarten (Dutch part)', 'sx'),
('SY', 'SYR', '760', 'Syrian Arab Republic', 'sy'),
('SZ', 'SWZ', '748', 'Eswatini', 'sz'),
('TC', 'TCA', '796', 'Turks and Caicos Islands', 'tc'),
('TD', 'TCD', '148', 'Chad', 'td'),
('TF', 'ATF', '260', 'French Southern Territories', 'tf'),
('TG', 'TGO', '768', 'Togo', 'tg'),
('TH', 'THA', '764', 'Thailand', 'th'),
('TJ', 'TJK', '762', 'Tajikistan', 'tj'),
('TK', 'TKL', '772', 'Tokelau', 'tk'),
('TL', 'TLS', '626', 'Timor-Leste', 'tl'),
('TM', 'TKM', '795', 'Turkmenistan', 'tm'),
('TN', 'TUN', '788', 'Tunisia', 'tn'),
('TO', 'TON', '776', 'Tonga', 'to'),
('TR', 'TUR', '792', 'Türkiye', 'tr'),
('TT', 'TTO', '780', 'Trinidad and Tobago', 'tt'),
('TV', 'TUV', '798', 'Tuvalu', 'tv'),
('TW', 'TWN', '158', 'Taiwan, Province of China', 'tw'),
('TZ', 'TZA', '834', 'Tanzania, United Republic of', 'tz'),
('UA', 'UKR', '804', 'Ukraine', 'ua'),
('UG', 'UGA', '800', 'Uganda', 'ug'),
('UM', 'UMI', '581', 'United States Minor Outlying Islands', 'um'),
('US', 'USA', '840', 'United States of America', 'us'),
('UY', 'URY', '858', 'Uruguay', 'uy'),
('UZ', 'UZB', '860', 'Uzbekistan', 'uz'),
('VA', 'VAT', '336', 'Holy See', 'va'),
('VC', 'VCT', '670', 'Saint Vincent and the Grenadines', 'vc'),
('VE', 'VEN', '862', 'Venezuela, Bolivarian Republic of', 've'),
('VG', 'VGB', '092', 'Virgin Islands (British)', 'vg'),
('VI', 'VIR', '850', 'Virgin Islands (U.S.)', 'vi'),
('VN', 'VNM', '704', 'Viet Nam', 'vn'),
('VU', 'VUT', '548', 'Vanuatu', 'vu'),
('WF', 'WLF', '876', 'Wallis and Futuna', 'wf'),
('WS', 'WSM', '882', 'Samoa', 'ws'),
('YE', 'YEM', '887', 'Yemen', 'ye'),
('YT', 'MYT', '175', 'Mayotte', 'yt'),
('ZA', 'ZAF', '710', 'South Africa', 'za'),
('ZM', 'ZMB', '894', 'Zambia', 'zm'),
('ZW', 'ZWE', '716', 'Zimbabwe', 'zw');
COMMIT;