-- *************************************************************************************************
--   This source member will insert language codes and names into lngmstt. This information comes
-- from ISO 639-1.
--
-- @author James Brian Hill
-- @copyright Copyright (c) 2015 - 2025 by James Brian Hill
-- @license GNU General Public License version 3
-- @link https://www.gnu.org/licenses/gpl-3.0.html
-- *************************************************************************************************

-- *************************************************************************************************
--   This program is free software: you can redistribute it and/or modify it under the terms of the
-- GNU General Public License as published by the Free Software Foundation, either version 3 of the
-- License, or (at your option) any later version.
--
--   This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
-- without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-- GNU General Public License for more details.
--
--   You should have received a copy of the GNU General Public License along with this program. If
-- not, see https://www.gnu.org/licenses/gpl-3.0.html
-- *************************************************************************************************
INSERT INTO lngt (id, dsc, dsc_native) VALUES
('aa', 'Afar', 'Afaraf'),
('ab', 'Abkhaz', 'аҧсуа бызшәа, аҧсшәа'),
('ae', 'Avestan', 'avesta'),
('af', 'Afrikaans', 'Afrikaans'),
('ak', 'Akan', 'Akan'),
('am', 'Amharic', 'አማርኛ'),
('an', 'Aragonese', 'aragonés'),
('ar', 'Arabic', 'العربية'),
('as', 'Assamese', 'অসমীয়া'),
('av', 'Avaric', 'авар мацӀ, магӀарул мацӀ'),
('ay', 'Aymara', 'aymar aru'),
('az', 'Azerbaijani', 'azərbaycan dili'),
('ba', 'Bashkir', 'башҡорт теле'),
('be', 'Belarusian', 'беларуская мова'),
('bg', 'Bulgarian', 'български език'),
('bh', 'Bihari', 'भोजपुरी'),
('bi', 'Bislama', 'Bislama'),
('bm', 'Bambara', 'bamanankan'),
('bn', 'Bengali, Bangla', 'বাংলা'),
('bo', 'Tibetan Standard, Tibetan, Central', 'བོད་ཡིག'),
('br', 'Breton', 'brezhoneg'),
('bs', 'Bosnian', 'bosanski jezik'),
('ca', 'Catalan', 'català'),
('ce', 'Chechen', 'нохчийн мотт'),
('ch', 'Chamorro', 'Chamoru'),
('co', 'Corsican', 'corsu, lingua corsa'),
('cr', 'Cree', 'ᓀᐦᐃᔭᐍᐏᐣ'),
('cs', 'Czech', 'čeština, český jazyk'),
('cu', 'Old Church Slavonic, Church Slavonic, Old Bulgarian', 'ѩзыкъ словѣньскъ'),
('cv', 'Chuvash', 'чӑваш чӗлхи'),
('cy', 'Welsh', 'Cymraeg'),
('da', 'Danish', 'dansk'),
('de', 'German', 'Deutsch'),
('dv', 'Divehi, Dhivehi, Maldivian', 'ދިވެހި'),
('dz', 'Dzongkha', 'རྫོང་ཁ'),
('ee', 'Ewe', 'Eʋegbe'),
('el', 'Greek (modern)', 'ελληνικά'),
('en', 'English', 'English'),
('eo', 'Esperanto', 'Esperanto'),
('es', 'Spanish', 'Español'),
('et', 'Estonian', 'eesti, eesti keel'),
('eu', 'Basque', 'euskara, euskera'),
('fa', 'Persian (Farsi)', 'فارسی'),
('ff', 'Fula, Fulah, Pulaar, Pular', 'Fulfulde, Pulaar, Pular'),
('fi', 'Finnish', 'suomi, suomen kieli'),
('fj', 'Fijian', 'vosa Vakaviti'),
('fo', 'Faroese', 'føroyskt'),
('fr', 'French', 'français, langue française'),
('fy', 'Western Frisian', 'Frysk'),
('ga', 'Irish', 'Gaeilge'),
('gd', 'Scottish Gaelic, Gaelic', 'Gàidhlig'),
('gl', 'Galician', 'galego'),
('gn', 'Guaraní', 'Avañe''ẽ'),
('gu', 'Gujarati', 'ગુજરાતી'),
('gv', 'Manx', 'Gaelg, Gailck'),
('ha', 'Hausa', '(Hausa) هَوُسَ'),
('he', 'Hebrew (modern)', 'עברית'),
('hi', 'Hindi', 'हिन्दी, हिंदी'),
('ho', 'Hiri Motu', 'Hiri Motu'),
('hr', 'Croatian', 'hrvatski jezik'),
('ht', 'Haitian, Haitian Creole', 'Kreyòl ayisyen'),
('hu', 'Hungarian', 'magyar'),
('hy', 'Armenian', 'Հայերեն'),
('hz', 'Herero', 'Otjiherero'),
('ia', 'Interlingua', 'Interlingua'),
('id', 'Indonesian', 'Bahasa Indonesia'),
('ie', 'Interlingue', 'Originally called Occidental; then Interlingue after WWII'),
('ig', 'Igbo', 'Asụsụ Igbo'),
('ii', 'Nuosu', 'ꆈꌠ꒿ Nuosuhxop'),
('ik', 'Inupiaq', 'Iñupiaq, Iñupiatun'),
('io', 'Ido', 'Ido'),
('is', 'Icelandic', 'Íslenska'),
('it', 'Italian', 'Italiano'),
('iu', 'Inuktitut', 'ᐃᓄᒃᑎᑐᑦ'),
('ja', 'Japanese', '日本語 (にほんご)'),
('jv', 'Javanese', 'ꦧꦱꦗꦮ, Basa Jawa'),
('ka', 'Georgian', 'ქართული'),
('kg', 'Kongo', 'Kikongo'),
('ki', 'Kikuyu, Gikuyu', 'Gĩkũyũ'),
('kj', 'Kwanyama, Kuanyama', 'Kuanyama'),
('kk', 'Kazakh', 'қазақ тілі'),
('kl', 'Kalaallisut, Greenlandic', 'kalaallisut, kalaallit oqaasii'),
('km', 'Khmer', 'ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ'),
('kn', 'Kannada', 'ಕನ್ನಡ'),
('ko', 'Korean', '한국어'),
('kr', 'Kanuri', 'Kanuri'),
('ks', 'Kashmiri', 'कश्मीरी, كشميري'),
('ku', 'Kurdish', 'Kurdî, كوردی'),
('kv', 'Komi', 'коми кыв'),
('kw', 'Cornish', 'Kernewek'),
('ky', 'Kyrgyz', 'Кыргызча, Кыргыз тили'),
('la', 'Latin', 'latine, lingua latina'),
('lb', 'Luxembourgish, Letzeburgesch', 'Lëtzebuergesch'),
('lg', 'Ganda', 'Luganda'),
('li', 'Limburgish, Limburgan, Limburger', 'Limburgs'),
('ln', 'Lingala', 'Lingála'),
('lo', 'Lao', 'ພາສາລາວ'),
('lt', 'Lithuanian', 'lietuvių kalba'),
('lu', 'Luba-Katanga', 'Tshiluba'),
('lv', 'Latvian', 'latviešu valoda'),
('mg', 'Malagasy', 'fiteny malagasy'),
('mh', 'Marshallese', 'Kajin M̧ajeļ'),
('mi', 'Māori', 'te reo Māori'),
('mk', 'Macedonian', 'македонски јазик'),
('ml', 'Malayalam', 'മലയാളം'),
('mn', 'Mongolian', 'Монгол хэл'),
('mr', 'Marathi (Marāṭhī)', 'मराठी'),
('ms', 'Malay', 'bahasa Melayu, بهاس ملايو'),
('mt', 'Maltese', 'Malti'),
('my', 'Burmese', 'ဗမာစာ'),
('na', 'Nauruan', 'Dorerin Naoero'),
('nb', 'Norwegian Bokmål', 'Norsk bokmål'),
('nd', 'Northern Ndebele', 'isiNdebele'),
('ne', 'Nepali', 'नेपाली'),
('ng', 'Ndonga', 'Owambo'),
('nl', 'Dutch', 'Nederlands, Vlaams'),
('nn', 'Norwegian Nynorsk', 'Norsk nynorsk'),
('no', 'Norwegian', 'Norsk'),
('nr', 'Southern Ndebele', 'isiNdebele'),
('nv', 'Navajo, Navaho', 'Diné bizaad'),
('ny', 'Chichewa, Chewa, Nyanja', 'chiCheŵa, chinyanja'),
('oc', 'Occitan', 'occitan, lenga d''òc'),
('oj', 'Ojibwe, Ojibwa', 'ᐊᓂᔑᓈᐯᒧᐎᓐ'),
('om', 'Oromo', 'Afaan Oromoo'),
('or', 'Oriya', 'ଓଡ଼ିଆ'),
('os', 'Ossetian, Ossetic', 'ирон æвзаг'),
('pa', '(Eastern) Punjabi', 'ਪੰਜਾਬੀ'),
('pi', 'Pāli', 'पाऴि'),
('pl', 'Polish', 'język polski, polszczyzna'),
('ps', 'Pashto, Pushto', 'پښتو'),
('pt', 'Portuguese', 'Português'),
('qu', 'Quechua', 'Runa Simi, Kichwa'),
('rm', 'Romansh', 'rumantsch grischun'),
('rn', 'Kirundi', 'Ikirundi'),
('ro', 'Romanian', 'Română'),
('ru', 'Russian', 'Русский'),
('rw', 'Kinyarwanda', 'Ikinyarwanda'),
('sa', 'Sanskrit (Saṁskṛta)', 'संस्कृतम्'),
('sc', 'Sardinian', 'sardu'),
('sd', 'Sindhi', 'सिन्धी, سنڌي، سندھی'),
('se', 'Northern Sami', 'Davvisámegiella'),
('sg', 'Sango', 'yângâ tî sängö'),
('si', 'Sinhalese, Sinhala', 'සිංහල'),
('sk', 'Slovak', 'slovenčina, slovenský jazyk'),
('sl', 'Slovene', 'slovenski jezik, slovenščina'),
('sm', 'Samoan', 'gagana fa''a Samoa'),
('sn', 'Shona', 'chiShona'),
('so', 'Somali', 'Soomaaliga, af Soomaali'),
('sq', 'Albanian', 'Shqip'),
('sr', 'Serbian', 'српски језик'),
('ss', 'Swati', 'SiSwati'),
('st', 'Southern Sotho', 'Sesotho'),
('su', 'Sundanese', 'Basa Sunda'),
('sv', 'Swedish', 'svenska'),
('sw', 'Swahili', 'Kiswahili'),
('ta', 'Tamil', 'தமிழ்'),
('te', 'Telugu', 'తెలుగు'),
('tg', 'Tajik', 'тоҷикӣ, toçikī, تاجیکی'),
('th', 'Thai', 'ไทย'),
('ti', 'Tigrinya', 'ትግርኛ'),
('tk', 'Turkmen', 'Türkmen, Түркмен'),
('tl', 'Tagalog', 'Wikang Tagalog'),
('tn', 'Tswana', 'Setswana'),
('to', 'Tonga (Tonga Islands)', 'faka Tonga'),
('tr', 'Turkish', 'Türkçe'),
('ts', 'Tsonga', 'Xitsonga'),
('tt', 'Tatar', 'татар теле, tatar tele'),
('tw', 'Twi', 'Twi'),
('ty', 'Tahitian', 'Reo Tahiti'),
('ug', 'Uyghur', 'ئۇيغۇرچە, Uyghurche'),
('uk', 'Ukrainian', 'Українська'),
('ur', 'Urdu', 'اردو'),
('uz', 'Uzbek', 'Oʻzbek, Ўзбек, أۇزبېك'),
('ve', 'Venda', 'Tshivenḓa'),
('vi', 'Vietnamese', 'Tiếng Việt'),
('vo', 'Volapük', 'Volapük'),
('wa', 'Walloon', 'walon'),
('wo', 'Wolof', 'Wollof'),
('xh', 'Xhosa', 'isiXhosa'),
('yi', 'Yiddish', 'ייִדיש'),
('yo', 'Yoruba', 'Yorùbá'),
('za', 'Zhuang, Chuang', 'Saɯ cueŋƅ, Saw cuengh'),
('zh', 'Chinese', '中文 (Zhōngwén), 汉语, 漢語'),
('zu', 'Zulu', 'isiZulu');